// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhtYYCMiCm6melTdVokbFi7_aWWnHOzos',
    appId: '1:283167393304:web:70502c896aabe2f538256d',
    messagingSenderId: '283167393304',
    projectId: 'fitplus-fcad4',
    authDomain: 'fitplus-fcad4.firebaseapp.com',
    storageBucket: 'fitplus-fcad4.appspot.com',
    measurementId: 'G-CNDS7PKJ14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtrkSxwEkdwpEveVF57dtVVPeQJ0GAIys',
    appId: '1:283167393304:android:79aea4c89cd286f138256d',
    messagingSenderId: '283167393304',
    projectId: 'fitplus-fcad4',
    storageBucket: 'fitplus-fcad4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt8o1gfo9t-jMLVI_N6P3OR1v_Hp71WFs',
    appId: '1:283167393304:ios:7e4fcf3d0054749538256d',
    messagingSenderId: '283167393304',
    projectId: 'fitplus-fcad4',
    storageBucket: 'fitplus-fcad4.appspot.com',
    iosClientId: '283167393304-s9v8s454lp4vhn7u8q97ovqhpufpv6gt.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt8o1gfo9t-jMLVI_N6P3OR1v_Hp71WFs',
    appId: '1:283167393304:ios:313f76baaa054e5d38256d',
    messagingSenderId: '283167393304',
    projectId: 'fitplus-fcad4',
    storageBucket: 'fitplus-fcad4.appspot.com',
    iosClientId: '283167393304-d4bm5q5hkcmme9jkkh6r0jsmf7cc5323.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitplus.RunnerTests',
  );
}
